version: '3'

services:
    node:
      build: .
      restart: on-failure
      env_file: .env
      volumes:
        - .:/app
        - /app/node_modules
      ports:
        - "80:${APP_PORT}"
        - "${APP_PORT}:${APP_PORT}"


